# Host names and passwords must be in sync with docker-compose.ci.yml
datasources:
  - id: postgresdb
    password: 
    url: "postgresql://postgres:{{env.PG_PASSWORD}}@adventureworks-postgres"
  - id: mysqldb
    url: "mysql://squealy:{{env.MYSQL_PASSWORD}}@mysql-57/squealy"
  - id: sqlitedb
    url: "sqlite:///:memory:"
  - id: mssqldb
    url: "mssql+pymssql://sa:{{ env.MSSQL_PASSWORD }}@mssql-2017:1433"
  - id: oracledb
    url: "oracle+cx_oracle://system:{{ env.ORACLE_PASSWORD }}@oracle-xe-11g:1521/xe"

cors:
  allowedOrigins:
    - "http://localhost:3000"
    
authentication:
  jwt:
    algorithm: RS256
    publicKeyPath: 'public.pem'
    