version: '3'
services:
  web:
    container_name: squealy
    build: .
    environment:
      DEBUG: "false"
      SECRET_KEY: secret
      PG_PASSWORD: squealypg
      MYSQL_PASSWORD: squealy1234
      MSSQL_PASSWORD: "yourStrong(@!)Password"
      LD_LIBRARY_PATH: /opt/oracle/instantclient_19_6
    ports:
    - "8000:8000"
    volumes: 
    - "./squealy/fixtures/basic_loading:/squealy"
    - "./drivers/instantclient_19_6:/opt/oracle/instantclient_19_6"
  adventureworks-postgres:
    container_name: adventureworks-postgres
    image: adventureworks
    environment:
      POSTGRES_PASSWORD: squealypg
  squealy-mysq-57:
    container_name: squealy-mysql-57
    image: mysql:5.7.29
    environment: 
      MYSQL_ROOT_PASSWORD: squealyRootPassword
      MYSQL_DATABASE: squealy
      MYSQL_USER: squealy
      MYSQL_PASSWORD: squealy1234
  squealy-mssql-2017:
    container_name: squealy-mssql-2017
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment: 
      ACCEPT_EULA: Y
      SA_PASSWORD: "yourStrong(@!)Password"
  squealy-oracle-xe-11g:
    container_name: squealy-oracle-xe-11g
    image: oracleinanutshell/oracle-xe-11g:latest