version: '3'
services:
  api:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    ports:
    - "5000:5000"
    volumes: 
    - "./:/code"
  dba.se.com:
    image: squealy/dba.se.com
    environment: 
      POSTGRES_PASSWORD: stackexchange