# Generated by Django 3.0.4 on 2020-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squealy', '0010_delete_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.IntegerField(choices=[(1, 'query'), (2, 'user')], default=1),
        ),
        migrations.AlterField(
            model_name='transformation',
            name='name',
            field=models.IntegerField(choices=[(1, 'Transpose'), (2, 'Split'), (3, 'Merge')], default=1),
        ),
    ]
