name: Integration Tests
on: [push]

jobs:
  build:
    name: docker-compose-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run the tests using docker-compose
        run: docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from tests
