name: Test & Publish
on: [push]
jobs:
  squealy-core:
    name: Squealy Core
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        python-versions: [3.5, 3.6, 3.7, 3.8]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.test.txt
      - name: Unit Tests
        run: python -m unittest discover -s tests
      
  squealy-app:
    name: Squealy App Integration Tests
    needs: squealy-core
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache-oracle-driver
        with:
          path: squealy-app/drivers/instantclient_19_6
          key: instantclient_19_6-cache-buster-1
      - name: Download Oracle Instantclient
        if: steps.cache-oracle-driver.outputs.cache-hit != 'true'
        run: curl -o instantclient.zip https://download.oracle.com/otn_software/linux/instantclient/19600/instantclient-basic-linux.x64-19.6.0.0.0dbru.zip && unzip instantclient.zip -d drivers
        working-directory: squealy-app
      - name: Run Integration Tests using docker-compose
        run: docker-compose -f docker-compose.ci.yml up --abort-on-container-exit --exit-code-from tests
        working-directory: squealy-app
  publish:
    name: Publish Docker Image
    needs: squealy-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: squealy/runtime
          workdir: squealy-app
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          snapshot: true